import { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/landing/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Momentum 💭</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>
    </>
  );
};

export default Home;
